/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 08-Aug-2020 18:11:22
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 30
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2017b.app/extern/include/tmwtypes.h 
 */
const int BL = 30;
const real64_T B[30] = {
   0.005076723094561, 0.005760257820009, 0.007777467824419,  0.01103466689407,
    0.01538004629999,   0.0206107698066,  0.02648246313858,  0.03272065345877,
    0.03903362276643,  0.04512607263168,  0.05071295947001,  0.05553285143139,
    0.05936018031974,  0.06201581372531,  0.06337545131844,  0.06337545131844,
    0.06201581372531,  0.05936018031974,  0.05553285143139,  0.05071295947001,
    0.04512607263168,  0.03903362276643,  0.03272065345877,  0.02648246313858,
     0.0206107698066,  0.01538004629999,  0.01103466689407, 0.007777467824419,
   0.005760257820009, 0.005076723094561
};
