/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 08-Aug-2020 18:09:18
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 30
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2017b.app/extern/include/tmwtypes.h 
 */
const int BL = 30;
const real64_T B[30] = {
   0.005059132502093, 0.005743480565085,  0.00775880510479,  0.01101341443068,
    0.01535710298033,  0.02058816052028,  0.02646282359805,  0.03270672442857,
    0.03902779712766,  0.04513003152357,  0.05072742402898,  0.05555746520665,
    0.05939352520541,  0.06205555017237,  0.06341856260549,  0.06341856260549,
    0.06205555017237,  0.05939352520541,  0.05555746520665,  0.05072742402898,
    0.04513003152357,  0.03902779712766,  0.03270672442857,  0.02646282359805,
    0.02058816052028,  0.01535710298033,  0.01101341443068,  0.00775880510479,
   0.005743480565085, 0.005059132502093
};
