/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 08-Aug-2020 18:10:49
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 30
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2017b.app/extern/include/tmwtypes.h 
 */
const int BL = 30;
const real64_T B[30] = {
   0.005029869812376, 0.005715557640986, 0.007727730036842,  0.01097801166521,
    0.01531886688972,  0.02055046389567,  0.02643006079221,  0.03268346849616,
    0.03901804381106,  0.04513659103458,  0.05075150536754,  0.05559847861024,
    0.05944910778938,  0.06212179952654,  0.06349044463148,  0.06349044463148,
    0.06212179952654,  0.05944910778938,  0.05559847861024,  0.05075150536754,
    0.04513659103458,  0.03901804381106,  0.03268346849616,  0.02643006079221,
    0.02055046389567,  0.01531886688972,  0.01097801166521, 0.007727730036842,
   0.005715557640986, 0.005029869812376
};
