/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 08-Aug-2020 18:12:10
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 30
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2017b.app/extern/include/tmwtypes.h 
 */
const int BL = 30;
const real64_T B[30] = {
   0.004989017466057, 0.005676547859308, 0.007684286932113,  0.01092848576668,
    0.01526534237057,  0.02049765837655,  0.02638412947998,  0.03265082438376,
    0.03900429690824,  0.04514569310718,  0.05078516396048,  0.05565587715715,
    0.05952693958332,  0.06221459456183,  0.06359114208678,  0.06359114208678,
    0.06221459456183,  0.05952693958332,  0.05565587715715,  0.05078516396048,
    0.04514569310718,  0.03900429690824,  0.03265082438376,  0.02638412947998,
    0.02049765837655,  0.01526534237057,  0.01092848576668, 0.007684286932113,
   0.005676547859308, 0.004989017466057
};
