/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 02-May-2020 20:38:18
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 30
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2017b.app/extern/include/tmwtypes.h 
 */
const int BL = 30;
const real64_T B[30] = {
   0.004936690866748, 0.005626533676114, 0.007628538054799,  0.01086487508882,
    0.01519653586089,  0.02042971411469,  0.02632496655762,  0.03260870639446,
    0.03898646408759,  0.04515725627291,   0.0508283442016,  0.05572964026369,
    0.05962703640287,  0.06233398088215,  0.06372071727504,  0.06372071727504,
    0.06233398088215,  0.05962703640287,  0.05572964026369,   0.0508283442016,
    0.04515725627291,  0.03898646408759,  0.03260870639446,  0.02632496655762,
    0.02042971411469,  0.01519653586089,  0.01086487508882, 0.007628538054799,
   0.005626533676114, 0.004936690866748
};
